// src/emit/codec/codecEmitter.ts
// The `codec` target: a canonical, byte-deterministic binary codec in TypeScript.
//
// The payload this produces carries end-to-end-encrypted data, so the server can
// never inspect or repair it. Anything the codec cannot encode correctly is
// rejected at generation time rather than encoded approximately.

import type { EmitContext, Emitter, OutputFile } from "../types.js";
import type { ResolvedSchema } from "../../resolver/types.js";
import { baseFieldsToEmit, overlayFieldsToEmit } from "../typeMapping.js";
import { CodecUnsupportedError } from "./errors.js";
import { planModel, type ModelPlan } from "./plan.js";
import { CODEC_RUNTIME } from "./runtimePrelude.js";
import { emitEnum, emitInterface, emitTagSets } from "./typeGen.js";
import { emitEncoder } from "./encoderGen.js";
import { emitDecoder, emitOneofReaders } from "./decoderGen.js";

const HEADER = [
  "// Generated by OpenSchema — canonical binary codec. Do not edit.",
  "// Wire format: docs/wire-format.md",
  "//",
  "// Encoding is canonical: identical data always produces identical bytes, so a",
  "// hash of the output can be used to detect real changes.",
].join("\n");

export const codecEmitter: Emitter = {
  target: "codec",
  fileExtension: "ts",

  emit(context: EmitContext): OutputFile[] {
    rejectOverlayCompany(context);
    rejectDuplicateLocalNames(context.schema);

    const blocks: string[] = [HEADER, CODEC_RUNTIME.trim()];

    // Shared by oneof readers, which have no per-message retired set.
    blocks.push("const EMPTY_TAGS: ReadonlySet<number> = new Set([]);");

    for (const symbol of context.schema.enums.values()) {
      blocks.push(emitEnum(symbol));
    }

    for (const plan of planModels(context)) {
      blocks.push(emitInterface(plan));
      blocks.push(emitTagSets(plan));
      blocks.push(...emitOneofReaders(plan));
      blocks.push(emitEncoder(plan));
      blocks.push(emitDecoder(plan));
    }

    return [{ path: `schema.codec.${this.fileExtension}`, contents: `${blocks.join("\n\n")}\n` }];
  },
};

function planModels(context: EmitContext): ModelPlan[] {
  const plans: ModelPlan[] = [];
  for (const record of context.schema.records.values()) {
    // Generic records have unsubstituted type parameters, matching the zod target.
    if (record.isGeneric) continue;
    const fields = baseFieldsToEmit(record, context);
    plans.push(planModel(record, fields, context.schema));
  }
  return plans;
}

/**
 * Overlay ordinals live in their own space and start at 1, so a base field and
 * an overlay field routinely claim the same tag. Encoding both into one message
 * would be ambiguous.
 */
function rejectOverlayCompany(context: EmitContext): void {
  if (context.company === null) return;

  for (const record of context.schema.records.values()) {
    const overlay = overlayFieldsToEmit(context.schema, record, context.company);
    if (overlay.length === 0) continue;
    throw new CodecUnsupportedError("OSC005", record.symbol.localName, null,
      `the codec target cannot emit company overlays: overlay ordinals share the ` +
      `base record's tag space. Generate without --company.`,
      record.symbol.span);
  }
}

/**
 * Named types resolve by local name across every emitter, so two models called
 * `Name` in different namespaces would silently share generated functions — and
 * therefore cross-wire their encoders.
 */
function rejectDuplicateLocalNames(schema: ResolvedSchema): void {
  const seen = new Map<string, string>();

  for (const record of schema.records.values()) {
    reportDuplicate(seen, record.symbol.localName, record.symbol.qualifiedName, record.symbol.span);
  }
  for (const symbol of schema.enums.values()) {
    reportDuplicate(seen, symbol.localName, symbol.qualifiedName, symbol.span);
  }
}

function reportDuplicate(
  seen: Map<string, string>,
  localName: string,
  qualifiedName: string,
  span: { line: number; col: number },
): void {
  const existing = seen.get(localName);
  if (existing !== undefined) {
    throw new CodecUnsupportedError("OSC008", localName, null,
      `'${localName}' is declared in both '${existing}' and '${qualifiedName}'; ` +
      `the codec resolves named types by local name, so they would collide`,
      span);
  }
  seen.set(localName, qualifiedName);
}
